version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    container_name: devops-course-ntw-api-container
    image: devops-course-ntw-api
    # env_file: ./backend/.env
    expose:
      - 8000
    ports:
      - 8000:8000
    command: pm2-runtime ./index.js
    restart: unless-stopped
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    container_name: devops-course-ntw-ui-container
    image: devops-course-ntw-ui
    depends_on:
      - api
    env_file: ./frontend/.env
    environment:
      - VITE_API_URL=http://localhost:8000
    expose:
      - 80
    ports:
      - 80:80
